# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('when', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Heure de début')),
                ('deadline', models.DateTimeField(verbose_name='Deadline')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location', verbose_name='Lieu')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=5000, null=True)),
                ('attachement', models.FileField(blank=True, null=True, upload_to=events.models.rename_attach, verbose_name='Annexe(s)')),
                ('sent', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
    ]
